# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aef68515f4a707cbd9466f73250acbc67abc34682346330a28c1af195824b054d868d4d591f0748762d6f9fdbb0cc9227dbafac5e273e724c68dd4166863807

test:
  secret_key_base: a11f9b949172e19d9dcbe8322e21bece643c27148a209ed4c435aae88e0cca016551a3d5bc472fa2c9f61defbecf9311545143cb521e507c0a45d98f3514f9b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
